name: gorilla_hash
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-154.0.dev <3.0.0"

dependencies:
  animated_flip_counter: ^0.2.5
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.7
  dio: ^4.0.6
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  motion_toast: ^2.6.4
  package_info_plus: ^3.0.1
  provider: ^6.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - .env
